export default Object.freeze({
  /** Alphabetic */
  0x04:"mdi-alpha-a",
  0x05:"mdi-alpha-b",
  0x06:"mdi-alpha-c",
  0x07:"mdi-alpha-d",
  0x08:"mdi-alpha-e",
  0x09:"mdi-alpha-f",
  0x0A:"mdi-alpha-g",
  0x0B:"mdi-alpha-h",
  0x0C:"mdi-alpha-i",
  0x0D:"mdi-alpha-j",
  0x0E:"mdi-alpha-k",
  0x0F:"mdi-alpha-l",
  0x10:"mdi-alpha-m",
  0x11:"mdi-alpha-n",
  0x12:"mdi-alpha-o",
  0x13:"mdi-alpha-p",
  0x14:"mdi-alpha-q",
  0x15:"mdi-alpha-r",
  0x16:"mdi-alpha-s",
  0x17:"mdi-alpha-t",
  0x18:"mdi-alpha-u",
  0x19:"mdi-alpha-v",
  0x1A:"mdi-alpha-w",
  0x1B:"mdi-alpha-x",
  0x1C:"mdi-alpha-y",
  0x1D:"mdi-alpha-z",
  0x1E:"mdi-numeric-1",
  0x1F:"mdi-numeric-2",
  0x20:"mdi-numeric-3",
  0x21:"mdi-numeric-4",
  0x22:"mdi-numeric-5",
  0x23:"mdi-numeric-6",
  0x24:"mdi-numeric-7",
  0x25:"mdi-numeric-8",
  0x26:"mdi-numeric-9",
  0x27:"mdi-numeric-0",
  /** Basic Functions */
  0x28: "mdi-keyboard-return",
  0x29: "mdi-keyboard-esc",
  0x2A:"mdi-keyboard-backspace",
  0x2B:"mdi-keyboard-tab",
  0x2C:"mdi-keyboard-space",
  0x2D:"mdi-minus",
  0x2E:"mdi-equal",
  // 0x2F: "fa-solid fa-bracket-square-left",
  // 0x30:"fa-solid fa-bracket-square-right",
  // 0x31:"fa-solid fa-slash-back",
  // 0x33:"fa-solid fa-semicolon",
  0x34: "mdi-format-quote-close",
  // 0x35:"fa-solid fa-accent-grave",
  0x36:"mdi-comma",
  0x37:"mdi-circle-small",
  0x38:"mdi-slash-forward",
  0x39:"mdi-keyboard-caps",
  /** Basic Macros */
  0x3A:"mdi-keyboard-f1",
  0x3B:"mdi-keyboard-f2",
  0x3C:"mdi-keyboard-f3",
  0x3D:"mdi-keyboard-f4",
  0x3E:"mdi-keyboard-f5",
  0x3F:"mdi-keyboard-f6",
  0x40:"mdi-keyboard-f7",
  0x41:"mdi-keyboard-f8",
  0x42:"mdi-keyboard-f9",
  0x43:"mdi-keyboard-f10",
  0x44:"mdi-keyboard-f11",
  0x45:"mdi-keyboard-f12",
  /** Controls */
  0x46:"mdi-monitor-screenshot",
  0x47:"mdi-arrow-vertical-lock",
  0x48:"mdi-pause-octagon",
  0x49:"mdi-debug-step-into",
  0x4A:"mdi-page-first",
  0x4B:"mdi-arrow-expand-up",
  0x4C:"mdi-delete-sweep",
  0x4D:"mdi-page-last",
  0x4E:"mdi-arrow-expand-down",
  /** Directions */
  0x4F:"mdi-arrow-right",
  0x50:"mdi-arrow-left",
  0x51:"mdi-arrow-down",
  0x52:"mdi-arrow-up",
  /** Numpad */
  0x53:"mdi-numeric",
  0x54:"mdi-slash-forward-box",
  0x55:"mdi-multiplication-box",
  0x56:"mdi-minus-box",
  0x57:"mdi-plus-box",
  0x58:"mdi-arrow-down-box",
  0x59:"mdi-numeric-1-box",
  0x5A:"mdi-numeric-2-box",
  0x5B:"mdi-numeric-3-box",
  0x5C:"mdi-numeric-4-box",
  0x5D:"mdi-numeric-5-box",
  0x5E:"mdi-numeric-6-box",
  0x5F:"mdi-numeric-7-box",
  0x60:"mdi-numeric-8-box",
  0x61:"mdi-numeric-9-box",
  0x62:"mdi-numeric-0-box",
  0x63:"mdi-circle-box",
  /** Extra Functions */
  0x65:"mdi-apps",
  // 0x68:"F13",
  // 0x69:"F14",
  // 0x6A:"F15",
  // 0x6B:"F16",
  // 0x6C:"F17",
  // 0x6D:"F18",
  // 0x6E:"F19",
  // 0x6F:"F20",
  // 0x70:"F21",
  // 0x71:"F22",
  // 0x72:"F23",
  // 0x73:"F24",
  /** Basic Auxiliaries */
  // 0xE0:"LCtrl",
  // 0xE1:"LShift",
  // 0xE2:"LAlt",
  // 0xE3:"LMeta",
  // 0xE4:"RCtrl",
  // 0xE5:"RShift",
  // 0xE6:"RAlt",
  // 0xE7:"RMeta",
  /** Volume Controls */
  0x80:"mdi-volume-mute",
  0x81:"mdi-volume-plus",
  0x82:"mdi-volume-minus",
  // NumpadEqual: "mdi-equal-box",
  // NumpadComma: "mdi-comma-box",
  // KanaMode: "mdi-syllabary-katakana",
  // MediaTrackPrevious: "mdi-skip-backward",
  // MediaTrackNext: "mdi-skip-forward",
  // MediaPlayPause: "mdi-pause",
  // MediaStop: "mdi-stop",
  // MediaSelect: "mdi-folder-play",
  // ContextMenu: "mdi-menu",
  // Power: "mdi-power",
  // Sleep: "mdi-power-sleep",
  // WakeUp: "mdi-lightbulb-on",
  // BrowserHome: "mdi-web",
  // BrowserSearch: "mdi-file-search",
  // BrowserFavorites: "mdi-file-star",
  // BrowserRefresh: "mdi-file-refresh",
  // BrowserStop: "mdi-file-remove",
  // BrowserForward: "mdi-file-rotate-right",
  // BrowserBack: "mdi-file-rotate-left",
});
